#!/bin/bash
# Ramos Sign Tools for Linux
# Authour: @librehat
# My Blog : https://www.librehat.com
# My English Blog: http://en.librehat.com
#

if [ ! $2 ] ; then
  echo "You must specify two parameters!"
  echo "hatmod_signtool [OPTION] [FILENAME]"
  echo "OPTIONS: unzip, zip"
  echo "i.e.    ./hatmod_signtool zip hatmod_2.0_beta5.zip"
  exit 1
fi
option=$1
filename=$2

function extract
{
	if [ ! -e $filename ];then
		echo "ERROR: No $filename found."
		echo "You need put the $filename file in this directory at first."
		exit 1
	fi
	echo "Extracting..."
	if [ -d Temp ];then
		rm -rf Temp
	fi
	mkdir Temp
	if unzip -q $filename -d Temp;then
		echo "Extracted."
	else
		echo "ERROR occurs when unzip the $filename"
	fi
}

function compressnsign
{
	if [ ! -d Temp ] || [ ! -r Temp ];then
		echo "Error while attempting to read Temp"
		exit 1
	fi
	echo "Compressing..."
	if [ -e intermediate_unsigned.zip ];then
		rm -f intermediate_unsigned.zip
	fi
	if `cd Temp && zip -1 -q ../intermediate_unsigned.zip -r *` ;then
		echo "Signing..."
		if [ -e $filename ];then
			if [ -e $filename.bak ];then
				rm -f $filename.bak
			fi
			mv $filename $filename.bak
		fi
		java -Xmx999m -jar other/signapk.jar -w other/testkey.x509.pem other/testkey.pk8 intermediate_unsigned.zip $filename
		rm -f intermediate_unsigned.zip
		echo "Done."
	else
		echo "ERROR occurs while compressing."
	fi
}

if [ $option = "unzip" ];then
	extract
elif [ $option = "zip" ];then
	compressnsign
else
	echo "UNKNOWN OPTION"
fi
